# Use this values to install SiteWhere using rook-ceph-block storageClass
# usage: helm install --name sitewhere -f values-rook-ceph.values sitewhere/sitewhere

sitewhere-infra-core:
  cp-kafka:
    persistence:
      storageClass: rook-ceph-block
  cp-zookeeper:
    persistence:
      dataDirStorageClass: rook-ceph-block
      dataLogDirStorageClass: rook-ceph-block
  postgresql:
    persistence:
      storageClass: rook-ceph-block
      
sitewhere-infra-database: 
  mongodb:
    persistence:
      storageClass: rook-ceph-block
  cassandra:
    persistence:
      storageClass: rook-ceph-block
  influxdb:
    persistence:
      storageClass: rook-ceph-block
  # 2020/01/19 Tony: When I used k8s to start with ceph, I found that the absence of this in the value-rook-ceph.yaml file caused the PVC of tenantsdb to be in the pending state, so I added
  tenantsdb:
    persistence:
      storageClass: rook-ceph-block
